services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=amigosecreto
    volumes:
      - postgresql_data:/bitnami/postgresql

volumes:
  postgresql_data:
